name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - run: |
        git fetch --prune --unshallow
    - name: Install deps 🔧
      run: |
        curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
        sudo luet install -y extension/package-browser
    - name: Build pages 🔧
      run: |
        sudo -E luet-package-browser --config config.yaml --output build --templates templates
        sudo cp -rfv CNAME build/
    - name: Deploy GH Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.9.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
        single-commit: true
